name: Sync release
on:
  release:
    types: [published]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: KernelSU-Modules-Repo/encore
          event-type: sync-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "version": "${{ github.event.release.tag_name }}"}'
